### ISSUE TITLE
Deploying on Windows Server

### ISSUE THREAD

**Issue by CptPirx** [willibrandon/spellcheck32#1]
Hi,
thanks for publishing this package, very useful! 

I've successfully used it in environemnts where I have admin privileges. However, I need to deploy an app, using your package, to a Windows std server. There an issue beocmes apparent: spellcheck32 needs permissions to watch and modify the MS dictionary. I do not have those permission on the server.

My question is: is there any way to disable the funcionalities that need those permissions to modify the dicitonary?

**Comment by willibrandon** [comment]
Interesting. Were you aware that I install a user-specific US English dictionary for the Added word list if the specified language tag is "en-US"? Perhaps I should not do that by default, especially if it requires admin privileges.

**Comment by willibrandon** [comment]
@CptPirx - Please update to version 1.0.5-alpha and let me know if that alleviates your issue.

**Comment by CptPirx** [comment]
Hi, thanks for responding, I appreciate that!

Unfortunately, this fix does not resolve the issue. In my logs I get the same errors, namely:

- "Cannot track changes to the user word list: The parameter is incorrect. The spell checking function will remain available, but change reporting will not work."
- "Cannot track changes to spelling check options: Access is denied. The spell checking function will remain available, but change reporting will not work."

This happens when initializing the spell checker:
`spellCheckerTargetLanguage = new SpellChecker(languageTag);`

The errors in the logs give impression that this should work but with limited funcionality. However, the spell checker fails to initialise. 
As before, this works without issues on my PC with admin privileges.

**Comment by willibrandon** [comment]
Could you provide any additional details on how I might reproduce your environment? I have tried reproducing this issue with a low privileged account on Windows Server and thus far have been unsuccessful. The spell checker still seems to work for me so there is probably something that I am missing here.

**Comment by CptPirx** [comment]
Hi, these errors were resolved today by elevating the app on the server from 'ApplicationPoolIdentity' to 'NetworkService'. I'll let you know if this means that everything is now working as expected soon!

**Comment by willibrandon** [comment]
I believe I know what the issue is now. The error:

`Cannot track changes to the user word list: The parameter is incorrect. The spell checking function will remain available, but change reporting will not work.`

Gets thrown when an attempt is made to initialize the event handler using a low privileged user on this line here.
https://github.com/willibrandon/spellcheck32/blob/5b22cb4d5c0f203396fc734e606f9b25f47a793a/src/spellcheck32/SpellChecker.cs#L88

I can make a change to catch exceptions that occur when initializing this event handler, allowing the spell checker to still work, although change reporting will be disabled. This approach and resulting behavior in this scenario will have the exact result mentioned in the error message.

`The spell checking function will remain available, but change reporting will not work.`

I'll see if I can get a fix in for this issue at some point today.

**Comment by willibrandon** [comment]
@CptPirx - Please update to version [1.0.6-alpha](https://github.com/willibrandon/spellcheck32/releases/tag/v1.0.6-alpha) and let me know if it alleviates your issue.
